#BASE IMAGE
FROM node:14.3.0-stretch as react-build

#WORKDIR
WORKDIR /app

# install and cache app dependencies
COPY package*.json ./
COPY config-overrides.js ./
COPY ./public ./public
COPY ./src ./src

RUN rm -rf node_modules
RUN npm install

# Bundle app source
COPY . .

EXPOSE 3000

